(function(){
 'use strict';
 if(location.pathname.replace(/\/+$/,'')!=='/privacy-policy')return;
 function mount(){
  if(document.getElementById('bw-arrival-privacy-v2'))return;
  const main=document.querySelector('main');if(!main)return;
  const section=document.createElement('section');section.id='bw-arrival-privacy-v2';section.setAttribute('aria-labelledby','bw-arrival-privacy-title');
  section.style.cssText='box-sizing:border-box;max-width:900px;width:calc(100% - 40px);margin:36px auto;padding:28px;background:#fafaf5;color:#212121;border:1px solid #c5e1a5;border-radius:22px;font:16px/1.65 Montserrat,Arial,sans-serif;grid-column:1 / -1;';
  section.innerHTML='<h2 id="bw-arrival-privacy-title" style="color:#1b5e20;font:800 28px/1.25 Montserrat,Arial,sans-serif;margin:0 0 16px">Berlin Arrival Card and occasional Berlin emails</h2><p>Specific privacy information · Effective 4 October 2026</p><p><strong>Controller:</strong> Yusuf Ucuz. <a href="https://walkofberlin.com/contact">Contact me</a>. The controller details and rights in the main Privacy Policy apply.</p><h3>The form and your choice</h3><p>The Arrival Card form uses a visible explanation below the email field and button. It has no consent checkbox. Clicking “Send me the card” records your request and your consent to receive the Arrival Card and occasional Berlin tips and offers from Walk of Berlin by email. The displayed explanation is:</p><blockquote>By clicking “Send me the card”, you agree to receive the Arrival Card and occasional Berlin tips and offers from Walk of Berlin by email. You can unsubscribe at any time.</blockquote><p>The legal basis is your consent. The email subscription is recorded when you submit. For a first request, you receive an email verification link before the card download opens. If your email address is already confirmed, I send a secure access link. Verification links expire after seven days; access links expire after 48 hours.</p><h3>Data and delivery</h3><p>I record your email address, the consent text and version, request and confirmation times, source page, delivery status and unsubscribe status. The consent version identifies the button submission and its visible explanation; I do not record a checkbox as checked. Confirmation tokens are stored as hashes. Wix stores restricted request and subscription records, Vercel processes the request, and Google/Gmail delivers the email under the applicable provider data-protection terms.</p><h3>Unsubscribe and retention</h3><p>You can withdraw using the unsubscribe link in the request email or a later email, including before opening the card. This stops the subscription and revokes remaining card access. The active subscription and the information required to operate it are retained while the subscription is active. Limited consent and suppression records may be retained as described in the main Privacy Policy to document your choice and respect an unsubscribe. Withdrawal does not affect processing already carried out.</p><p>This section describes the Arrival Card form introduced on 4 October 2026. The separate choices and explanations for other forms remain specific to those forms.</p>';
  main.append(section);
 }
 mount();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});[500,1500,3000,6000].forEach(t=>setTimeout(mount,t));
})();
